# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: bocbang-fe-config
#   namespace: bocbang-fe
#   labels:
#     app: bocbang-fe
# data:
#   config.js: |
#    // Application Configuration
#     const config = {
#       NODE_ENV: "production",

#       // Next.js Configuration
#       NEXT_PUBLIC_API_URL: "https://api.localservices.democloud.xyz",
#       NEXT_PUBLIC_APP_NAME: "LocalServices Frontend",

#       // API Endpoints
#       API_BASE_URL: "https://api.localservices.democloud.xyz/v1",

#       // Feature Flags
#       NEXT_PUBLIC_ENABLE_ANALYTICS: "true",

#       // Other Configuration
#       PORT: "3000",
#       HOSTNAME: "0.0.0.0"
#     };

#     // Nếu dùng cho Client-side (gắn vào window)
#     if (typeof window !== 'undefined') {
#       window._CONFIG = config;
#     }
#     // Nếu dùng cho Server-side (Node.js)
#     if (typeof module !== 'undefined') {
#       module.exports = config;
#     }
# ---
apiVersion: v1
kind: Namespace
metadata:
  name: bocbang-fe
  labels:
    project: my-project

---
# Kubernetes Secrets
# Generated by Kube Composer
# Total Secrets: 1

apiVersion: v1
kind: Secret
metadata:
  name: aws-bocbang-secret
  namespace: bocbang-fe
  labels:
    project: my-project
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyIyOTY3MjUzNTU4NzAuZGtyLmVjci5hcC1zb3V0aGVhc3QtMS5hbWF6b25hd3MuY29tIjp7InVzZXJuYW1lIjoiQVdTIiwicGFzc3dvcmQiOiJleUp3WVhsc2IyRmtJam9pVjFCUlRUbGtZMVp4TWswMVJESTNORE5EYWtSSldDdGpkMVZ1WW5sa2VWRXlSekZrZVdFd1NYbFRTV2cwY1hZMVEySmtTaTg0ZW5wU1VXdDZNbmRyTUhOSU1IQm9NVlUxSzBwTFl6RmhRbFJvV0d0Q1FscFhiVXBtTldKamNEQlFWMHhLU0hGa0szSm9SU3QyU2k5d1dIaFBSRkZaUzJOTFkwczBkV3RwWkdKMWMyNXNRMFptUWk5TlF5c3hTbG80Y1VGcFMxcHNkMXBYVTBWb2RHWlpOelZxT1ZOeWRVVjFiWGxTTjFJME9IcFVhVVl4VUdWTmQySjFUVU15V25NeGJtNDBiREphWkRrM1R6QkpWV2RQZDJwV05VcHllbk5SV0c5clRubHhPVEEzU0N0UU4wZHVkbEpJUVRONldqVjVja2RUZURoMFF6Vk1RV2RoVURZd2VHeGhWV05NTmtaSGVGUmlkMnBTVFZSc09WQk1jMm95WjNoYVIxZGFTVGhEWm5oSlkyRmhTVFZTTlVaSWNtY3ZOVWc0WlZSNE1ETjNjVTh4ZGpCRWNXNUJOM2xaZWtreVV6aFRXR3h5ZG5oUlpETjRTemN4SzJGdVMwODFiVGRaUlZWRU5YUm1RMjV2WkhjeFFtOTVWWFpXSzBKUmIyVjZWMlZUYVhVeFYyWndTVVphYkUxb2FuSmtUMWR5ZEM5dmNWb3ZObkJ5TDBRd1drZGlkelZWTUdkUVFtdE5UM05RTm1wd1FrSkZTVXg2VGpoR2RrcDFSMkpzTW1wV2NsUnRUMFJ0VDJWUVNtZGxOR1l3VUU5bmNFVkVRWGh1WjJ4TFdHbzROWEpOTUcxd2RWQnJUVnBXVkdOaU1YQXdNbko1TUV4d05VbE1TVTFGT1V4SE0wbGpkamd2YkV0cVkxazJWRlJrT1hKWFJrOWtkbVY1TTJJeVEwSXZkbEYyVFdsT1RXUnFXa1J6TlRaV1IyTkphRWRJUlVodVkwOHZWV0o1U3psdlExRXJSMmRwYUhsamFraE1kM0JUWTBjMGIybENUVXROY3psR1pVWjBUM05tYkdONU5YbExUMDVKVUZCa1VqTkJZa2QxTmtwS1oxcEZORTFsWTB3MVYzUnpNRWRKWlVwVldITXJSMVZMSzNRdmFVdzJRVXM1VFc1dlZVNVFjR0ZVTjNkbWNEbG1TMHBpVW5aMWVVUkNSVWMwZUVSdlFtVTNVbWR5T0RsTlFTOTRkRlYzZWxKdWRrZFJORzA0UVU5cVdXaDVXR0k0ZVhsR1NUZFZZMmhVWVU1cFNGbzFRM0ZpVVhoSGFrZHBTa0ZuVUM4MWFuQXhkVTVVZVdOcVNTdHJVVWN4WTNGeVdWVnVNRlJMY1c5Q0sxaGtkRTlKUlZCUGVVOTRNbHBvVjJKNlFtcHJabkZYY0VaTkt6aDFMemh3V2xsTVJtaEhObUZ1YTNoVFdUUnJXV2wyZWtzcmF5OTRaRGhuVEdFM2JtNVdhVnBzTWtrdlFYQm1Xak5pU1hrclJ6Uk1kVlp6UW1OamNXTlVORlYzYm5od2NIcE5kbk5ZZUVjd1RIcENWM2R3Y1dGdlNteEpXVE4yVmxaTWQwVkhOVEk0YVZsV2RVNWtNMDlxVGtZemN6VTFiRWhsV2tSSFVXRnJOSGRaY0ZZM05HRnVPVEZ5SzFBMWMyRXdUUzlhVVhsalJrdFZWVzUxUkVGMmFFVXhVRTFGUVZnemRYVjNXR0ZzV0c5d1QwVjNRakZ0VmxoQ2IyVTJSRTh6VlZwTVZVbEVUMmswT1dGWGVsRk5RM1pQTjJKS0wxaHlZbkZqVm5GNlRrSkJWVUpSYmpoTFFrTnhOa053ZEZGWlVFMTRWazRpTENKa1lYUmhhMlY1SWpvaVFWRkZRa0ZJYVdSRmNscERabWhMVDJWRVRUQTRLMk5RTldaMGVXcDJVVGxZVFUxVFVUUndTekJHV201MlFWcFlTbWRCUVVGSU5IZG1RVmxLUzI5YVNXaDJZMDVCVVdOSGIwYzRkMkpSU1VKQlJFSnZRbWRyY1docmFVYzVkekJDUW5kRmQwaG5XVXBaU1ZwSlFWZFZSRUpCUlhWTlFrVkZSRXBuWTFST2FFOXhUSEZ3Wlc5M1NYVkJTVUpGU1VFM2NVTnlibWR3TjBGSWJWSkVXV0ZwV0c4dlpHWXlaRWwxUkRadVZrRmhlVzUzTTBRMFMzWmhNRGd2UzFwSWFIbHFLMWxZVlRJMmNWSkVXVUpCUmtjMU1GQlZlbFJCYW14c1ZHMVVNVzlpWXowaUxDSjJaWEp6YVc5dUlqb2lNaUlzSW5SNWNHVWlPaUpFUVZSQlgwdEZXU0lzSW1WNGNHbHlZWFJwYjI0aU9qRTNOamsyTVRnd05EbDkiLCJlbWFpbCI6IiIsImF1dGgiOiJRVmRUT21WNVNuZFpXR3h6WWpKR2EwbHFiMmxXTVVKU1ZGUnNhMWt4V25oTmF6QXhVa1JKTTA1RVRrUmhhMUpLVjBOMGFtUXhWblZaYm14clpWWkZlVko2Um10bFYwVjNVMWhzVkZOWFp6QmpXRmt4VVRKS2ExTnBPRFJsYm5CVFZWZDBOazF1WkhKTlNFNUpUVWhDYjAxV1ZURkxNSEJNV1hwR2FGRnNVbTlYUjNSRFVXeHdXR0pWY0cxT1YwcHFZMFJDVVZZd2VFdFRTRVpyU3pOS2IxSlRkREpUYVRsM1YwaG9VRkpHUmxwVE1rNU1XVEJ6TUdSWGRIQmFSMG94WXpJMWMxRXdXbTFSYVRsT1VYbHplRk5zYnpSalZVWndVekZ3YzJReGNGaFZNRlp2WkVkYVdrNTZWbkZQVms1NVpGVldNV0pZYkZOT01Va3dUMGh3VldGVldYaFZSMVpPWkRKS01WUlZUWGxYYmsxNFltMDBNR0pFU21GYVJHc3pWSHBDU2xaWFpGQmtNbkJYVGxWd2VXVnVUbEpYUnpseVZHNXNlRTlVUVROVFEzUlJUakJrZFdSc1NrbFJWRTQyVjJwV05XTnJaRlJsUkdnd1VYcFdUVkZYWkdoVlJGbDNaVWQ0YUZaWFRrMU9hMXBJWlVaU2FXUXljRk5VVmxKelQxWkNUV015YjNsYU0yaGhVakZrWVZOVWFFUmFibWhLV1RKR2FGTlVWbE5PVlZwSlkyMWpkazVWWnpSYVZsSTBUVVJPTTJOVk9IaGtha0pGWTFjMVFrNHpiRnBsYTJ0NVZYcG9WRmRIZUhsa2JtaFNXa1JPTkZONlkzaExNa1oxVXpBNE1XSlVaRnBTVmxaRlRsaFNiVkV5TlhaYVNHTjRVVzA1TlZaWVdsZExNRXBTWWpKV05sWXlWbFJoV0ZWNFZqSmFkMU5WV21GaVJURnZZVzVLYTFReFpIbGtRemwyWTFadmRrNXVRbmxNTUZGM1YydGthV1I2VmxaTlIyUlJVVzEwVGxRelRsRk9iWEIzVVd0S1JsTlZlRFpVYW1oSFpHdHdNVkl5U25OTmJYQlhZMnhTZEZRd1VuUlVNbFpSVTIxa2JFNUhXWGRWUlRsdVkwVldSVkZZYUhWYU1uaE1WMGR2TkU1WVNrNU5SekYzWkZaQ2NsUldjRmRXUjA1cFRWaEJkMDF1U2pWTlJYaDNUbFZzVFZOVk1VWlBWWGhJVFRCc2FtUnFaM1ppUlhSeFdURnJNbFpHVW10UFdFcFlVbXM1YTJSdFZqVk5Na2w1VVRCSmRtUnNSakpVVjJ4UFZGZFNjVmRyVW5wT1ZGcFhVakpPU21GRlpFbFNWV2gxV1RBNGRsWlhTalZUZW14MlVURkZjbEl5WkhCaFNHeHFZV3RvVFdRelFsUlpNR013WWpKc1ExUlZkRTVqZW14SFdsVmFNRlF6VG0xaVIwNDFUbGhzVEZRd05VcFZSa0pyVldwT1FsbHJaREZPYTNCTFdqRndSazVGTVd4Wk1IY3hWak5TZWsxRlpFcGFWWEJXVjBoTmNsSXhWa3hMTTFGMllWVjNNbEZWY3pWVVZ6VjJWbFUxVVdOSFJsVk9NMlJ0WTBSc2JWTXdjR2xWYmxveFpWVlNRMUpWWXpCbFJWSjJVVzFWTTFWdFpIbFBSR3hPVVZNNU5HUkdWak5sYkVwMVpHdGtVazVITURSUlZUbHhWMWRvTlZkSFNUUmxXR3hIVTFSa1Zsa3lhRlZaVlRWd1UwWnZNVkV6Um1sVldHaElZV3RrY0ZOclJtNVZRemd4WVc1QmVHUlZOVlZsVjA1eFUxTjBjbFZWWTNoWk0wWjVWMVpXZFUxR1VreGpWemxEU3pGb2EyUkZPVXBTVmtKUVpWVTVORTFzY0c5V01rbzJVVzF3Y2xwdVJsaGpSVnBPUzNwb01VeDZhSGRYYkd4TlVtMW9TRTV0Um5WaE0yaFVWMVJTY2xkWGJESmxhM055WVhrNU5GcEVhRzVVUjBVelltMDFWMkZXY0hOTmEydDJVVmhDYlZkcVRtbFRXR3R5VW5wU1RXUldXbnBSYlU1cVkxZE9WVTVHVmpOaWJtaDNZMGh3VG1SdVRsbGxSV04zVkVod1ExWXpaSGRqVjBaMlUyMTRTbGRVVGpKV2JGcE5aREJXU0U1VVNUUmhWbXhYWkZVMWEwMHdPWEZVYTFsNlkzcFZNV0pGYUd4WGExSklWVmRHY2s1SVpGcGpSbGt6VGtkR2RVOVVSbmxMTVVFeFl6SkZkMVJUT1dGVldHeHFVbXQwVmxaWE5URlNSVVl5WVVWVmVGVkZNVVpSVm1kNlpGaFdNMWRIUm5OWFJ6bDNWREJXTTFGcVJuUldiR2hEWWpKVk1sSkZPSHBXVm5CTlZsVnNSVlF5YXpCUFYwWllaV3hHVGxFeldsQk9Na3BMVERGb2VWbHVSbXBXYmtZMlZHdEtRbFpWU2xKaWFtaE1VV3RPZUU1clRuZGtSa1phVlVVeE5GWnJOR2xNUTBwcldWaFNhR0V5VmpWSmFtOXBVVlpHUmxGclJrbGhWMUpHWTJ4d1JGcHRhRXhVTWxaRlZGUkJORXN5VGxGT1Yxb3daVmR3TWxWVWJGbFVWVEZVVlZSU2QxTjZRa2RYYlRVeVVWWndXVk50WkVKUlZVWkpUa2hrYlZGV2JFdFRNamxoVTFkb01sa3dOVUpWVjA1SVlqQmpOR1F5U2xKVFZVcENVa1ZLZGxGdFpISmpWMmh5WVZWak5XUjZRa05SYm1SR1pEQm9ibGRWY0ZwVFZuQktVVlprVmxKRlNrSlNXRlpPVVd0V1JsSkZjRzVaTVZKUFlVVTVlRlJJUm5kYVZ6a3pVMWhXUWxOVlNrWlRWVVV6WTFWT2VXSnRaSGRPTUVaSllsWktSVmRYUm5CWFJ6aDJXa2RaZVZwRmJERlNSRnAxVm10R2FHVlhOVE5OTUZFd1V6TmFhRTFFWjNaVE1YQkpZVWhzY1VzeGJGbFdWRWt5WTFaS1JWZFZTa0pTYTJNeFRVWkNWbVZzVWtKaGJYaHpWa2N4VlUxWE9XbFplakJwVEVOS01scFlTbnBoVnpsMVNXcHZhVTFwU1hOSmJsSTFZMGRWYVU5cFNrVlJWbEpDV0RCMFJsZFRTWE5KYlZZMFkwZHNlVmxZVW5CaU1qUnBUMnBGTTA1cWF6Sk5WR2QzVGtSc09RPT0ifX19
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bocbang-fe
  name: bocbang-fe-deployment
  namespace: bocbang-fe
spec:
  replicas: 2
  revisionHistoryLimit: 11
  selector:
    matchLabels:
      app: bocbang-fe
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bocbang-fe
      namespace: bocbang-fe
    spec:
      containers:
        - image: 296725355870.dkr.ecr.ap-southeast-1.amazonaws.com/bocbang-fe/bocbang-fe-image
          imagePullPolicy: Always
          name: bocbang-fe
          ports:
            - containerPort: 8080
              name: tcp
              protocol: TCP
          # volumeMounts:
          #   - mountPath: /app/www/config.js
          #     name: config-volume
          #     subPath: config.js
      imagePullSecrets:
        - name: aws-bocbang-secret
      # volumes:
      #   - configMap:
      #       defaultMode: 420
      #       name: bocbang-fe-config
      #     name: config-volume
---
apiVersion: v1
kind: Service
metadata:
  name: bocbang-fe-service
  namespace: bocbang-fe
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8887
      protocol: TCP
      targetPort: 8080
  selector:
    app: bocbang-fe
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bocbang-fe-ingress
  namespace: bocbang-fe
spec:
  ingressClassName: nginx
  rules:
    - host: www.tranthanhdat.xyz
      http:
        paths:
          - backend:
              service:
                name: bocbang-fe-service
                port:
                  number: 8887
            path: /boc-bang-AI
            pathType: Prefix
