---
- name: Cấu hình Nginx Load Balancer
  hosts: lb_servers
  become: yes
  vars:
    domain_name: "myapp.example.com"

  tasks:
    - name: Fix Ubuntu mirror (avoid AWS 503)
      replace:
        path: /etc/apt/sources.list.d/ubuntu.sources
        regexp: "http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu"
        replace: "http://archive.ubuntu.com/ubuntu"

    - name: Update apt cache after mirror fix
      apt:
        update_cache: yes
    - name: Cài đặt Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy cấu hình từ Jinja2 template
      template:
        src: nginx_lb.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
