- hosts: all
  name: fetch kubeconfig file
  gather_facts: false
  become: yes
  tasks:
    # Bỏ become: yes
    - name: Fix Ubuntu mirror (avoid AWS 503)
      replace:
        path: /etc/apt/sources.list.d/ubuntu.sources
        regexp: "http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu"
        replace: "http://archive.ubuntu.com/ubuntu"

    - name: Update apt cache after mirror fix
      apt:
        update_cache: yes
    - name: fetch kubeconfig file
      ansible.builtin.fetch:
        src: /home/ubuntu/.kube/config
        dest: ~/.kube/config # Dùng ~ thay vì hardcode
        flat: yes
        mode: "0600" # Quan trọng: kubeconfig phải restrict permission
