- hosts: all
  name: fetch kubeconfig file
  gather_facts: false
  become: yes
  tasks:
    - name: fetch kubeconfig file
      ansible.builtin.fetch:
        src: /home/ubuntu/.kube/config
        dest: ~/.kube/config
        flat: yes
        mode: "0600"
    # - name: fetch kubeconfig file to this source folder
    #   ansible.builtin.fetch:
    #     src: /home/ubuntu/.kube/config
    #     dest: ./kubeconfig
    #     flat: yes
    #     mode: "0600"
