- hosts: all
  name: fetch join token file
  gather_facts: false
  become: yes
  tasks:
    - name: Fix Ubuntu mirror (avoid AWS 503)
      replace:
        path: /etc/apt/sources.list.d/ubuntu.sources
        regexp: "http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu"
        replace: "http://archive.ubuntu.com/ubuntu"

    - name: Update apt cache after mirror fix
      apt:
        update_cache: yes
    - name: fetch join token file
      ansible.builtin.fetch:
        src: /home/ubuntu/join-command.sh
        dest: ./join-command.sh
        flat: yes
    - name: fetch join token file for master
      ansible.builtin.fetch:
        src: /home/ubuntu/join-command-master.sh
        dest: ./join-command-master.sh
        flat: yes
    # - name: fetch nodeport of ingress-nginx
    #   ansible.builtin.fetch:
    #     src: /home/ubuntu/nodeport.txt
    #     dest: ./nodeport.txt
    #     flat: yes
