- name: Setup NFS Server
  hosts: all
  gather_facts: yes
  become: yes # Chạy với quyền sudo
  vars:
    nfs_dir: "/mnt/k8s-nfs"
    allowed_network: "10.0.0.0/16"

  tasks:
    - name: Cập nhật apt cache và cài đặt nfs-kernel-server
      ansible.builtin.apt:
        name: nfs-kernel-server
        state: present
        update_cache: yes

    - name: Tạo thư mục chia sẻ và phân quyền
      ansible.builtin.file:
        path: "{{ nfs_dir }}"
        state: directory
        owner: nobody
        group: nogroup
        mode: "0777"

    - name: Cấu hình file /etc/exports
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "{{ nfs_dir }} {{ allowed_network }}(rw,sync,no_subtree_check,no_root_squash)"
        create: yes
      notify: Reload NFS

    - name: Đảm bảo dịch vụ NFS đang chạy và tự khởi động
      ansible.builtin.systemd:
        name: nfs-kernel-server
        state: started
        enabled: yes

    # - name: Mở port NFS (2049) trên tường lửa UFW
    #   community.general.ufw:
    #     rule: allow
    #     src: "{{ allowed_network }}"
    #     port: "2049"
    #     proto: any
    #   ignore_errors: yes

  handlers:
    - name: Reload NFS
      ansible.builtin.command: exportfs -arv
      notify: Restart NFS

    - name: Restart NFS
      ansible.builtin.systemd:
        name: nfs-kernel-server
        state: restarted
