- name: Install Helm
  hosts: all
  become: yes # required for moving binary to system path

  tasks:
    - name: Fix Ubuntu mirror (avoid AWS 503)
      replace:
        path: /etc/apt/sources.list.d/ubuntu.sources
        regexp: "http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu"
        replace: "http://archive.ubuntu.com/ubuntu"

    - name: Update apt cache after mirror fix
      apt:
        update_cache: yes
    - name: Download Helm installer script
      ansible.builtin.uri:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        return_content: true
      register: helm_installer

    - name: Run Helm installer script
      ansible.builtin.command:
        cmd: bash
        stdin: "{{ helm_installer.content }}"
        creates: /usr/local/bin/helm
      environment:
        DESIRED_VERSION: "" # Installs the latest version
