---
- name: Install Docker Official (Debian Bookworm)
  hosts: all
  become: yes # Chạy với quyền sudo

  vars:
    # Định nghĩa các package cũ cần gỡ bỏ
    old_packages:
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
      - containerd
      - runc

    # Định nghĩa các package mới cần cài
    new_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

    keyring_path: /etc/apt/keyrings/docker.asc
    repo_file_path: /etc/apt/sources.list.d/docker.sources

  tasks:
    # BƯỚC QUAN TRỌNG: Xóa bỏ các cấu hình lỗi cũ để tránh treo apt update
    - name: Clean up old incorrect Docker source files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/docker.list
        - "{{ repo_file_path }}" # Xóa file hiện tại để đảm bảo ghi mới hoàn toàn

    # 1. Gỡ bỏ các phiên bản Docker cũ
    - name: Remove conflicting/old packages
      apt:
        name: "{{ old_packages }}"
        state: absent
        purge: yes

    # 2. Cài đặt các gói phụ thuộc (Bây giờ apt update sẽ chạy mượt)
    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes
    # 1. Gỡ bỏ các phiên bản Docker cũ
    - name: Remove conflicting/old packages
      apt:
        name: "{{ old_packages }}"
        state: absent
        purge: yes

    # 2. Cài đặt các gói phụ thuộc
    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    # 3. Tạo thư mục keyrings
    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    # 4. Tải GPG Key (Đã đổi URL sang debian)
    - name: Download Docker's official GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: "{{ keyring_path }}"
        mode: "0644"

    # 5. Thêm Repository (Đã đổi URI sang debian)
    - name: Add Docker repository to Apt sources
      copy:
        dest: "{{ repo_file_path }}"
        content: |
          Types: deb
          URIs: https://download.docker.com/linux/debian
          Suites: {{ ansible_distribution_release }}
          Components: stable
          Signed-By: {{ keyring_path }}
      register: repo_added

    # 6. Cài đặt Docker
    - name: Install Docker packages
      apt:
        name: "{{ new_packages }}"
        state: present
        update_cache: yes

    # 7. Khởi động Docker Service
    - name: Ensure Docker service is running and enabled
      service:
        name: docker
        state: started
        enabled: yes

    # 8. Thêm user hiện tại vào nhóm docker
    - name: Add current user to docker group
      user:
        name: "{{ ansible_user | default(ansible_env.USER) }}"
        groups: docker
        append: yes
