---
- name: Cài đặt và cấu hình NGINX Web Server
  hosts: local
  become: yes # Chạy với quyền sudo
  gather_facts: yes
  vars:
    nginx_port: 80
    server_name: localhost

  tasks:
    - name: Cập nhật danh sách gói phần mềm (apt update)
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Cài đặt gói NGINX
      apt:
        name: nginx
        state: present

    - name: Đảm bảo thư mục web root tồn tại
      file:
        path: /var/www/html
        state: directory
        mode: "0755"
        owner: www-data
        group: www-data

    - name: Tạo file index.html mẫu để test
      copy:
        content: "<h1>Hello từ NGINX được cài bởi Ansible!</h1>"
        dest: /var/www/html/index.html
        mode: "0644"
    - name: Đảm bảo NGINX đang chạy và tự khởi động cùng hệ thống
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Kiểm tra trạng thái NGINX (Health Check)
      uri:
        url: "http://localhost"
        status_code: 200
      register: result

    - name: Hiển thị thông báo thành công
      debug:
        msg: "NGINX đã sẵn sàng! Phản hồi từ server: {{ result.status }}"
