---
- hosts: h2q-105
  become: true
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: install apache2 package
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"
    - name: add php support
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
