- name: Copy file to remote server
  hosts: gcloud
  gather_facts: yes
  # become: true
  tasks:
    - name: Copy config file
      ansible.builtin.copy:
        src: "~/.kube/config" # path on your control node
        dest: "{{ ansible_user_dir }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"
    - name: Debug chỉ khi verbose
      ansible.builtin.debug:
        var: ansible_facts.user_dir
        verbosity: 2
