- name: Copy file join-command-master.sh to master node
  hosts: all
  become: yes
  tasks:
    - name: Fix Ubuntu mirror (avoid AWS 503)
      replace:
        path: /etc/apt/sources.list.d/ubuntu.sources
        regexp: "http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu"
        replace: "http://archive.ubuntu.com/ubuntu"

    - name: Update apt cache after mirror fix
      apt:
        update_cache: yes
    - name: Copy file join-command-master.sh to master node
      ansible.builtin.copy:
        src: ./join-command-master.sh # Đường dẫn file trên máy bạn
        dest: /home/ubuntu/join-command-master.sh # Đường dẫn trên Server
        owner: ubuntu # Chủ sở hữu
        group: ubuntu # Nhóm
        mode: "0777" # Phân quyền (r--r--r--)
        backup: yes # Tự động tạo bản backup nếu file cũ đã tồn tại
