apiVersion: storage.k8s.io/v1
kind: StorageClass
annotations:
  storageclass.kubernetes.io/is-default-class: "true" # Đặt làm mặc định
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com # Driver chuẩn hiện nay
parameters:
  type: gp3
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer # Chỉ tạo ổ khi có Pod thực sự cần (tránh lỗi lệch Zone)
allowVolumeExpansion: true # Cho phép mở rộng dung lượng sau này
