replicaCount: 1

image:
  registry: 296725355870.dkr.ecr.ap-southeast-1.amazonaws.com
  repository: isc/isc-be-image
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: isc-be-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {} # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: backend.tranthanhdat.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Environment variables to be injected via ConfigMap
env:
  API_URL: "http://localhost:8888"
  CORS_ORIGIN: "*"
  DB_HOST: "database-1.cbswiyaoaxz0.ap-southeast-1.rds.amazonaws.com"
  DB_NAME: "postgres"
  DB_PASSWORD: "28062002"
  DB_PORT: "5432"
  DB_SYNC: "true"
  DB_USER: "postgres"
  EMAIL_FROM: "tranthanhdat4321@gmail.com12345678"
  EMAIL_FROM_NAME: "shopmini"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PASSWORD: "woav yyvy xyhg vdos"
  EMAIL_PORT: "587"
  EMAIL_USERNAME: "tranthanhdat4321@gmail.com"
  FRONTEND_URL: "https://frontend.tranthanhdat.org"
  GEMINI_API_KEY: "AIzaSyBN6o8CHTCbpooSfO2xT0d2Gx2vyJlGpC8"
  JWT_EXPIRES_IN: "1d"
  JWT_REFRESH_EXPIRES_IN: "7d"
  JWT_REFRESH_SECRET: "your_jwt_refresh_secret_key"
  JWT_SECRET: "your_jwt_secret_key"
  MAX_FILE_SIZE: "5242880"
  NODE_ENV: "development"
  PAYOS_API_KEY: "89453335-016f-471a-815a-c0b400913ccd"
  PAYOS_CHECKSUM_KEY: "ec38dcd379268b75e18c25cc00858f593e4d1137b85009ca2eae92a0cb40e7b1"
  PAYOS_CLIENT_ID: "cb57b91b-5ae8-4da8-996c-d1fde5cc06c8"
  PORT: "8888"
  REDIS_HOST: "localhost"
  REDIS_PASSWORD: ""
  REDIS_PORT: "6379"
  UPLOAD_DIR: "uploads"
